apiVersion: v1
kind: Service
metadata:
  labels:
    app: mcp
  name: svc-mcp
  namespace: default
spec:
  type: LoadBalancer
  ports:
  - port: 5001
  selector:
    app: mcp
---
apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: mcp 
  name: mcp
  namespace: default
spec:
  replicas: 1
  selector:
    matchLabels:
      app: mcp
  template:
    metadata:
      labels:
        app: mcp
    spec:
      containers:
      - name: mcp
        image: developeronizuka/mcp:1.0.0
        imagePullPolicy: Always
        #command: ["sleep", "infinity"]
        ports:
        - containerPort: 5001
        env:
        - name: FACE_RECOGNIZER_URL
          value: "http://face-recognizer-api-svc:5000/facerecognizer"
