apiVersion: v1
kind: Service
metadata:
  labels:
    app: face-recognizer-api
  name: face-recognizer-api-svc
  namespace: default
spec:
  type: LoadBalancer
  ports:
  - port: 5000
  selector:
    app: face-recognizer-api
---
apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: face-recognizer-api
  name: face-recognizer-api
  namespace: default
spec:
  replicas: 1
  selector:
    matchLabels:
      app: face-recognizer-api
  template:
    metadata:
      labels:
        app: face-recognizer-api
    spec:
      containers:
      - name: face-recognizer-api
        image: python:3.11-slim
        command: ["sleep", "infinity"]
        ports:
        - containerPort: 5000
